server:
  port: 8089
spring:
  application:
    name: cart-service
  jackson:
    default-property-inclusion: non_null #告诉jackson如果某个属性的值为null，请不要封装
  redis:
    host: 192.168.206.66

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间

logging:
  level:
    com.leyou: debug

ly:
  jwt:
    pubKeyPath: D:/heima/rsa/id_rsa.pub # D:/heima/rsa/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN