server:
  port: 8087
spring:
  application:
    name: auth-service
  redis:
    host: 192.168.206.66
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima88
    username: root
    password: root



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5 #心跳周期
    lease-expiration-duration-in-seconds: 15 #过期时间

ly:
  jwt:
    pubKeyPath: E:/secret/rsa/id_rsa.pub # # 公钥地址
    priKeyPath: E:/secret/rsa/id_rsa # # 私钥地址
    user:
      expire: 30 # 过期时间,单位分钟
      cookieName: LY_TOKEN # cookie名称
      cookieDomain: leyou.com # cookie的域
      cookieMaxAge: 1800 #cookie过期时间
    app:
      expire: 1500 #过期时间25小时
      id: 10
      secret: auth-service
      headerName: heima88

  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid
      strength: 10 # 加密强度4~31，决定了密码和盐加密时的运算次数，超过10以后加密耗时会显著增加
